<a href="https://colab.research.google.com/github/thomsonmukungu/0xvip3r/blob/main/DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
mukungu = pd.read_csv(r'/content/weather.csv')
print('shape of the dataset: ',mukungu.shape)
mukungu.head(100)

shape of the dataset:  (37, 65)

,S. No.,State/ UT,Fine - Total Acc. - 2014,Fine - Persons Killed - 2014,Fine - Persons Injured - 2014,Mist/fog - Total Acc. - 2014,Mist/fog - Persons Killed - 2014,Mist/fog - Persons Injured - 2014,Cloudy - Total Acc. - 2014,Cloudy - Persons Killed - 2014,...,Snowfall - Persons Injured - 2016,Hail/Sleet - Total Accidents - 2016,Hail/Sleet - Persons Killed - 2016,Hail/Sleet - Persons Injured - 2016,Dust Storm - Total Accidents - 2016,Dust Storm - Persons Killed - 2016,Dust Storm - Persons Injured - 2016,Others - Total Accidents - 2016,Others - Persons Killed - 2016,Others - Persons Injured - 2016
0,1,Andhra Pradesh,14591.0,4586,17065.0,724.0,219,925.0,647.0,188.0,...,0,92,45,137,42,34,61,2839,1086,3408
1,2,Arunachal Pradesh,71.0,30,110.0,14.0,10,26.0,11.0,8.0,...,0,12,7,13,0,0,0,44,22,91
2,3,Assam,3575.0,1318,3216.0,494.0,150,368.0,285.0,100.0,...,0,15,8,5,36,14,19,2188,763,1752
3,4,Bihar,2343.0,1218,1626.0,1713.0,881,1081.0,438.0,203.0,...,0,0,0,0,582,318,399,1820,1175,1247
4,5,Chhattisgarh,5000.0,1354,4584.0,382.0,149,376.0,863.0,216.0,...,0,0,0,0,132,28,151,3972,1262,3793
5,6,Goa,3556.0,257,1585.0,0.0,0,0.0,27.0,6.0,...,0,0,0,0,0,0,0,0,0,0
6,7,Gujarat,15008.0,4876,14431.0,643.0,176,639.0,1066.0,387.0,...,0,64,23,51,302,115,296,3160,1396,2924
7,8,Haryana,5519.0,2043,5261.0,724.0,263,716.0,310.0,160.0,...,0,70,75,175,243,150,363,893,444,667
8,9,Himachal Pradesh,2070.0,736,3635.0,90.0,45,232.0,195.0,96.0,...,10,0,0,0,0,0,0,0,0,0
9,10,Jammu & Kashmir,5290.0,816,7297.0,16.0,7,19.0,79.0,26.0,...,24,0,0,0,0,0,0,1238,208,1901
10,11,Jharkhand,1249.0,751,988.0,478.0,199,330.0,510.0,218.0,...,0,160,236,417,247,108,368,917,971,743
11,12,Karnataka,27346.0,6533,34052.0,1236.0,245,1899.0,1696.0,392.0,...,0,47,5,42,580,151,691,9218,2190,12041
12,13,Kerala,28138.0,3257,31627.0,477.0,28,561.0,1239.0,90.0,...,0,0,0,0,0,0,0,0,0,0
13,14,Madhya Pradesh,39335.0,6262,41623.0,2228.0,215,920.0,1436.0,342.0,...,0,426,86,639,429,68,751,5736,1098,6565
14,15,Maharashtra,55186.0,11099,36257.0,290.0,79,253.0,755.0,161.0,...,0,0,0,0,474,119,520,0,0,0
15,16,Manipur,228.0,72,379.0,38.0,6,66.0,33.0,5.0,...,0,10,0,20,3,0,5,0,0,0
16,17,Meghalaya,43.0,7,33.0,44.0,12,28.0,57.0,19.0,...,0,0,0,0,0,0,0,205,53,84
17,18,Mizoram,88.0,76,174.0,14.0,10,20.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
18,19,Nagaland,251.0,63,172.0,0.0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,28,20,47
19,20,Orissa,3713.0,1592,3930.0,670.0,259,749.0,691.0,300.0,...,0,47,27,42,249,95,318,1970,881,2169
20,21,Punjab,3631.0,2707,2188.0,891.0,605,636.0,246.0,163.0,...,0,0,0,0,69,39,59,21,12,23
21,22,Rajasthan,21567.0,8866,23996.0,611.0,328,496.0,240.0,77.0,...,0,28,24,31,8,4,5,1113,576,1230
22,23,Sikkim,58.0,17,98.0,47.0,12,54.0,0.0,0.0,...,18,9,0,0,0,0,0,34,6,12
23,24,Tamil Nadu,42716.0,10753,51344.0,1857.0,256,1786.0,2479.0,415.0,...,0,0,0,0,0,0,0,274,70,340
24,25,Telangana,10845.0,3622,11037.0,287.0,148,267.0,470.0,139.0,...,0,0,0,0,4,2,12,2580,785,2843
25,26,Tripura,551.0,139,913.0,39.0,15,115.0,43.0,13.0,...,0,0,0,0,0,0,0,25,11,30
26,27,Uttarakhand,1081.0,702,1226.0,95.0,48,91.0,33.0,18.0,...,6,32,21,18,9,5,13,132,95,215
27,28,Uttar Pradesh,11484.0,5865,7475.0,1454.0,860,964.0,1341.0,723.0,...,0,199,146,276,1521,759,1227,10843,5683,7074
28,29,West Bengal,4513.0,2187,5164.0,1533.0,650,942.0,538.0,213.0,...,0,6,6,8,196,109,521,0,0,0
29,30,A & N Islands,168.0,20,209.0,0.0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
30,31,Chandigarh,369.0,131,335.0,0.0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
31,32,D & N Haveli,47.0,34,50.0,0.0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,25,20,50
32,33,Daman & Diu,38.0,14,49.0,0.0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,3,1,6
33,34,Delhi,NaN,1656,NaN,NaN,11,NaN,NaN,NaN,...,0,171,23,165,122,27,114,2187,415,2036
34,35,Lakshadweep,0.0,0,0.0,0.0,0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
35,36,Puducherry,453.0,68,528.0,1.0,0,1.0,42.0,9.0,...,0,1,0,2,3,2,2,25,12,31
36,Total,Total,310121.0,83727,312657.0,17090.0,5886,14560.0,15770.0,4687.0,...,58,1389,732,2041,5251,2147,5895,51490,19255,51322

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


mukungu = pd.read_csv(r'/content/weather.csv')# Loading the dataset

mukungu.dropna(axis=0, inplace=True)

X = mukungu[['Mist/fog - Total Acc. - 2014', 'Cloudy - Total Acc. - 2014', 'Hail/Sleet - Total Accidents - 2016', 'Dust Storm - Total Accidents - 2016']]
y = mukungu[['Mist/fog - Total Acc. - 2014']]


# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



mukungu.dropna(axis=0,inplace=True)
kungu = LinearRegression()
kungu.fit(X, y)

LinearRegression()

In [4]:
print(mukungu)

   S. No.          State/ UT  Fine - Total Acc. - 2014  \
0       1     Andhra Pradesh                   14591.0
1       2  Arunachal Pradesh                      71.0
2       3              Assam                    3575.0
3       4              Bihar                    2343.0
4       5       Chhattisgarh                    5000.0
5       6                Goa                    3556.0
6       7            Gujarat                   15008.0
7       8            Haryana                    5519.0
8       9   Himachal Pradesh                    2070.0
9      10    Jammu & Kashmir                    5290.0
10     11          Jharkhand                    1249.0
11     12          Karnataka                   27346.0
12     13             Kerala                   28138.0
13     14     Madhya Pradesh                   39335.0
14     15        Maharashtra                   55186.0
15     16            Manipur                     228.0
16     17          Meghalaya                      43.0
17     18            Mizoram                      88.0
18     19           Nagaland                     251.0
19     20             Orissa                    3713.0
20     21             Punjab                    3631.0
21     22          Rajasthan                   21567.0
22     23             Sikkim                      58.0
23     24         Tamil Nadu                   42716.0
24     25          Telangana                   10845.0
25     26            Tripura                     551.0
26     27        Uttarakhand                    1081.0
27     28      Uttar Pradesh                   11484.0
28     29        West Bengal                    4513.0
29     30      A & N Islands                     168.0
30     31         Chandigarh                     369.0
31     32       D & N Haveli                      47.0
32     33        Daman & Diu                      38.0
34     35        Lakshadweep                       0.0
35     36         Puducherry                     453.0
36  Total              Total                  310121.0

    Fine - Persons Killed - 2014  Fine - Persons Injured - 2014  \
0                           4586                        17065.0
1                             30                          110.0
2                           1318                         3216.0
3                           1218                         1626.0
4                           1354                         4584.0
5                            257                         1585.0
6                           4876                        14431.0
7                           2043                         5261.0
8                            736                         3635.0
9                            816                         7297.0
10                           751                          988.0
11                          6533                        34052.0
12                          3257                        31627.0
13                          6262                        41623.0
14                         11099                        36257.0
15                            72                          379.0
16                             7                           33.0
17                            76                          174.0
18                            63                          172.0
19                          1592                         3930.0
20                          2707                         2188.0
21                          8866                        23996.0
22                            17                           98.0
23                         10753                        51344.0
24                          3622                        11037.0
25                           139                          913.0
26                           702                         1226.0
27                          5865                         7475.0
28                          2187                         5164.0
29                            20                          209.0
30                           131                          335.0
31                            34                           50.0
32                            14                           49.0
34                             0                            0.0
35                            68                          528.0
36                         83727                       312657.0

    Mist/fog - Total Acc. - 2014  Mist/fog - Persons Killed - 2014  \
0                          724.0                               219
1                           14.0                                10
2                          494.0                               150
3                         1713.0                               881
4                          382.0                               149
5                            0.0                                 0
6                          643.0                               176
7                          724.0                               263
8                           90.0                                45
9                           16.0                                 7
10                         478.0                               199
11                        1236.0                               245
12                         477.0                                28
13                        2228.0                               215
14                         290.0                                79
15                          38.0                                 6
16                          44.0                                12
17                          14.0                                10
18                           0.0                                 0
19                         670.0                               259
20                         891.0                               605
21                         611.0                               328
22                          47.0                                12
23                        1857.0                               256
24                         287.0                               148
25                          39.0                                15
26                          95.0                                48
27                        1454.0                               860
28                        1533.0                               650
29                           0.0                                 0
30                           0.0                                 0
31                           0.0                                 0
32                           0.0                                 0
34                           0.0                                 0
35                           1.0                                 0
36                       17090.0                              5886

    Mist/fog - Persons Injured - 2014  Cloudy - Total Acc. - 2014  \
0                               925.0                       647.0
1                                26.0                        11.0
2                               368.0                       285.0
3                              1081.0                       438.0
4                               376.0                       863.0
5                                 0.0                        27.0
6                               639.0                      1066.0
7                               716.0                       310.0
8                               232.0                       195.0
9                                19.0                        79.0
10                              330.0                       510.0
11                             1899.0                      1696.0
12                              561.0                      1239.0
13                              920.0                      1436.0
14                              253.0                       755.0
15                               66.0                        33.0
16                               28.0                        57.0
17                               20.0                         0.0
18                                0.0                         0.0
19                              749.0                       691.0
20                              636.0                       246.0
21                              496.0                       240.0
22                               54.0                         0.0
23                             1786.0                      2479.0
24                              267.0                       470.0
25                              115.0                        43.0
26                               91.0                        33.0
27                              964.0                      1341.0
28                              942.0                       538.0
29                                0.0                         0.0
30                                0.0                         0.0
31                                0.0                         0.0
32                                0.0                         0.0
34                                0.0                         0.0
35                                1.0                        42.0
36                            14560.0                     15770.0

    Cloudy - Persons Killed - 2014  ...  Snowfall - Persons Injured - 2016  \
0                            188.0  ...                                  0
1                              8.0  ...                                  0
2                            100.0  ...                                  0
3                            203.0  ...                                  0
4                            216.0  ...                                  0
5                              6.0  ...                                  0
6                            387.0  ...                                  0
7                            160.0  ...                                  0
8                             96.0  ...                                 10
9                             26.0  ...                                 24
10                           218.0  ...                                  0
11                           392.0  ...                                  0
12                            90.0  ...                                  0
13                           342.0  ...                                  0
14                           161.0  ...                                  0
15                             5.0  ...                                  0
16                            19.0  ...                                  0
17                             0.0  ...                                  0
18                             0.0  ...                                  0
19                           300.0  ...                                  0
20                           163.0  ...                                  0
21                            77.0  ...                                  0
22                             0.0  ...                                 18
23                           415.0  ...                                  0
24                           139.0  ...                                  0
25                            13.0  ...                                  0
26                            18.0  ...                                  6
27                           723.0  ...                                  0
28                           213.0  ...                                  0
29                             0.0  ...                                  0
30                             0.0  ...                                  0
31                             0.0  ...                                  0
32                             0.0  ...                                  0
34                             0.0  ...                                  0
35                             9.0  ...                                  0
36                          4687.0  ...                                 58

    Hail/Sleet - Total Accidents - 2016  Hail/Sleet - Persons Killed - 2016  \
0                                    92                                  45
1                                    12                                   7
2                                    15                                   8
3                                     0                                   0
4                                     0                                   0
5                                     0                                   0
6                                    64                                  23
7                                    70                                  75
8                                     0                                   0
9                                     0                                   0
10                                  160                                 236
11                                   47                                   5
12                                    0                                   0
13                                  426                                  86
14                                    0                                   0
15                                   10                                   0
16                                    0                                   0
17                                    0                                   0
18                                    0                                   0
19                                   47                                  27
20                                    0                                   0
21                                   28                                  24
22                                    9                                   0
23                                    0                                   0
24                                    0                                   0
25                                    0                                   0
26                                   32                                  21
27                                  199                                 146
28                                    6                                   6
29                                    0                                   0
30                                    0                                   0
31                                    0                                   0
32                                    0                                   0
34                                    0                                   0
35                                    1                                   0
36                                 1389                                 732

    Hail/Sleet - Persons Injured - 2016  Dust Storm - Total Accidents - 2016  \
0                                   137                                   42
1                                    13                                    0
2                                     5                                   36
3                                     0                                  582
4                                     0                                  132
5                                     0                                    0
6                                    51                                  302
7                                   175                                  243
8                                     0                                    0
9                                     0                                    0
10                                  417                                  247
11                                   42                                  580
12                                    0                                    0
13                                  639                                  429
14                                    0                                  474
15                                   20                                    3
16                                    0                                    0
17                                    0                                    0
18                                    0                                    0
19                                   42                                  249
20                                    0                                   69
21                                   31                                    8
22                                    0                                    0
23                                    0                                    0
24                                    0                                    4
25                                    0                                    0
26                                   18                                    9
27                                  276                                 1521
28                                    8                                  196
29                                    0                                    0
30                                    0                                    0
31                                    0                                    0
32                                    0                                    0
34                                    0                                    0
35                                    2                                    3
36                                 2041                                 5251

    Dust Storm - Persons Killed - 2016  Dust Storm - Persons Injured - 2016  \
0                                   34                                   61
1                                    0                                    0
2                                   14                                   19
3                                  318                                  399
4                                   28                                  151
5                                    0                                    0
6                                  115                                  296
7                                  150                                  363
8                                    0                                    0
9                                    0                                    0
10                                 108                                  368
11                                 151                                  691
12                                   0                                    0
13                                  68                                  751
14                                 119                                  520
15                                   0                                    5
16                                   0                                    0
17                                   0                                    0
18                                   0                                    0
19                                  95                                  318
20                                  39                                   59
21                                   4                                    5
22                                   0                                    0
23                                   0                                    0
24                                   2                                   12
25                                   0                                    0
26                                   5                                   13
27                                 759                                 1227

In [5]:
kungu = LinearRegression()
kungu.fit(X, y)

LinearRegression()

In [8]:
import joblib
import pandas as pd


loaded_model = joblib.load(r'/content/accidents_severity.pkl')# Load the machine learning model

newData = pd.DataFrame({'Mist/fog - Total Acc. - 2014': [15, 78, 20, 69],
                        'Cloudy - Total Acc. - 2014': [120, 74, 98, 29],
                        'Hail/Sleet - Total Accidents - 2016': [201, 259, 121, 79],
                        'Dust Storm - Total Accidents - 2016': [56, 259, 138, 199]})# Creating a DataFrame with hypothetical data

# Make predictions using the loaded model
preditions = loaded_model.predict(newData)

# Define thresholds for mapping
low_threshold = 21
high_threshold = 70

#print the predictions with values
results = []
for predition in preditions:
    if predition <= low_threshold:
        mapped_prediction = 'low'
    elif predition <= high_threshold:
        mapped_prediction = 'high'
    else:
        mapped_prediction = 'very high'
    results.append((predition, mapped_prediction))

for predition, mapped_prediction in results:
    print(f'Predicted Outcome: {predition}, Occurrence : {mapped_prediction}')

Predicted Outcome: [15.], Occurrence : low
Predicted Outcome: [78.], Occurrence : very high
Predicted Outcome: [20.], Occurrence : low
Predicted Outcome: [69.], Occurrence : high